---
- name: Change NPA password
  ansible.builtin.command: sh roles/get_npa_password/files/change_password_script.sh {{ npa_name }}
  register: change_password_result
  changed_when: change_password_result.rc != 0

- name: Handle password change result
  ansible.builtin.set_fact:
    npa_result:
      rc: '{{ change_password_result.rc }}'
      msg: "{{ change_password_result.stdout }}"
  when: change_password_result.rc == 0

- name: Skip NPA password change if not needed
  ansible.builtin.set_fact:
    npa_result:
      rc: '0'
      msg: "Skipped, no change needed"
  when: change_password_result.rc == 1

- name: Handle NPA password change error
  ansible.builtin.set_fact:
    npa_result:
      rc: '1'
      msg: "Error changing password"
  when: change_password_result.rc != 0 and change_password_result.rc != 1
