---
- name: Change NPA password
  include_tasks: change_password.yml
  vars:
    npa_name: "{{ npa.name }}"
  register: npa_result
  ignore_errors: yes

- name: Set NPA change ok flag
  set_fact:
    npa_change_ok: true
  when: npa_result.rc == 0

- name: Log NPA password change result
  debug:
    msg: "Password change for NPA {{ npa.name }} in module {{ module.name }}: {{ npa_result }}"